apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web-api
spec:
  
  selector:
    matchLabels:
      app: deploy-web-api
  template:
    metadata:
      labels:
        app: deploy-web-api
    spec:
      containers:
      - name: web-api
        image: afmaia/kube-news:{{TAG}}
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "Pg#123"
        - name: DB_HOST
          value: "postgres-service"
        